// <auto-generated />
using System;
using EP.Cryptocurrency.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EP.Cryptocurrency.Storage.Migrations
{
    [DbContext(typeof(CryptoDbContext))]
    [Migration("20191111073520_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EP.Cryptocurrency.Storage.Entities.Cryptocurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("CirculatingSupply")
                        .HasColumnType("decimal(25,6)");

                    b.Property<int>("CoinMarketCapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(25,6)");

                    b.Property<decimal?>("MaxSupply")
                        .HasColumnType("decimal(25,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal?>("PercentChange1h")
                        .HasColumnType("decimal(25,6)");

                    b.Property<decimal?>("PercentChange24h")
                        .HasColumnType("decimal(25,6)");

                    b.Property<decimal?>("PercentChange7d")
                        .HasColumnType("decimal(25,6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(25,6)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal?>("TotalSupply")
                        .HasColumnType("decimal(25,6)");

                    b.Property<decimal?>("Volume24h")
                        .HasColumnType("decimal(25,6)");

                    b.HasKey("Id");

                    b.HasIndex("CoinMarketCapId");

                    b.HasIndex("Rank");

                    b.ToTable("Cryptocurrency","crypto");
                });
#pragma warning restore 612, 618
        }
    }
}
